apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mirwin77-mirwin77-poi-map-app-dev
  annotations:
    argocd/app-name: mirwin77-mirwin77-poi-map-app-dev
    backstage.io/kubernetes-id: mirwin77-mirwin77-poi-map-app-dev
    backstage.io/kubernetes-namespace: mirwin77
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=mirwin77-mirwin77-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/mirwin77-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/mirwin77/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/mirwin77/deployments/mirwin77-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/mirwin77-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://mirwin77-poi-map-app-mirwin77.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/mirwin77"
  system: workshop-system-mirwin77
  consumesApis:
    - gateway-api-mirwin77
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-mirwin77
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/mirwin77"
